---
apiVersion: v1
kind: Service
metadata:
  name: my-container-service
spec:
  selector:
    app: my-container
  ports:
    - protocol: TCP
      port: 80        # The port that the service will expose
      targetPort: 80  # The port on the container that the service will forward to
  type: ClusterIP    # The type of the service (can be ClusterIP, NodePort, LoadBalancer, etc.)